title: Alan Matzumiya
email: alan.matzumiya@gmail.com
description: |   
  I'm Chemical Engineer with Master's Degree in Mathematics.
  My Top Skills are Data Analysis, Software Development and Web Design.
baseurl: ""
url: https://alanmatzumiya.github.io

bar-items:
  - {id: "home", icon: "home", size": "15%", text: "Home"}
  - {id: "about", icon: "user", size: "15%", text: "About"}
  - {id: "education", icon: "certificate", size: "25%", text: "Education"}
  - {id: "experience", icon: "suitcase", size: "25%", text: "Experience"}
  - {id: "contact", icon: "envelope", size: "20%", text: "Contact"}

section:
  main: sections/main.html
  header: sections/header.html
  about: sections/about.html
  skills: sections/skills.html
  education: sections/education.html
  experience: sections/experience.html
  contact: sections/contact.html

js: assets/js
css: assets/css
img: assets/img
favicon: assets/favicon.ico
banner: assets/img/banner.png

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - app
  - __pycache__

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
