title: Alan Matzumiya
email: alan.matzumiya@gmail.com
description: |   
  I'm Chemical Engineer with Master's Degree in Mathematics.
  My Top Skills are Data Analysis, Software Development and Web Design.
baseurl: ""
url: "<URL>"

section:
  main: sections/main.html
  header: sections/header.html
  about: sections/about.html
  skills: sections/skills.html
  education: sections/education.html
  experience: sections/experience.html
  contact: sections/contact.html

js: assets/js
css: assets/css
img: assets/img
favicon: assets/favicon.ico
banner: assets/img/banner.png

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - app
  - __pycache__
  
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
